version: "3"

services:
  sspanel:
    image: justinhimself/sspanel-uim:latest
    container_name: sspanel
    restart: always
    ports:
      - 80:80
    networks:
      - sspanel
    volumes:
      - ${PATH_TO_SITE}/web:/var/www/html
    environment:
      SSPANEL_KEY: ${SSPANEL_KEY}
      SSPANEL_BASEURL: ${SSPANEL_BASEURL}
      SSPANEL_APPNAME: ${SSPANEL_APPNAME}
      SSPANEL_ADMIN_EMAIL: ${SSPANEL_ADMIN_EMAIL}
      SSPANEL_ADMIN_PASSWORD: ${SSPANEL_ADMIN_PASSWORD}
      SSPANEL_DEBUG: ${SSPANEL_DEBUG}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  sspaneldb:
    image: mariadb:latest
    container_name: sspaneldb
    restart: always
    networks:
      - sspanel
    volumes:
      - ${PATH_TO_SITE}/db:/var/lib/mysql
    environment:
      MARIADB_MYSQL_LOCALHOST_USER: ${DB_USERNAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}

  sspanelredis:
    image: redis:latest
    container_name: sspanelredis
    restart: always
    networks:
      - sspanel

networks:
  sspanel: